# site settings
title: miriam
subtitle: nielsen
email: zentouro@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: #"/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: https://zentouro.ldeo.columbia.edu/ # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/zentouro
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: https://twitter.com/andrewbanchich
  Facebook:
  Slack:
  YouTube: https://youtube.com/zentouro

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
