# site settings
title: miriam
subtitle: nielsen
email: mknkvqgb #replaced email with formspree code
description: i'm a climate researcher & video journalist
baseurl: # "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: https://zentouro.ldeo.columbia.edu # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/zentouro
  github: https://github.com/zentouro
  GitLab:
  Google-Plus: 
  instagram: https://instagram.com/zentouro
  Instagram: https://instagram.com/zentouro
  LinkedIn: 
  Twitter: # https://twitter.com/zentouro
  Facebook:
  Slack:
  YouTube: https://youtube.com/zentouro
  youtube: https://youtube.com/zentouro
  ## these aren't showing up
  bluesky: https://bsky.app/profile/zentouro.info
  orcid: https://orcid.org/0000-0003-0037-294X
  google-scholar: https://scholar.google.com/citations?user=pNhZXOEAAAAJ&hl=en

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
